### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by FacundoEG** [FerDR89/Game#1]
Fer como estas? ahí revise el juego y anda re bien! no note nada raro ni fuera de lugar, así que para mi es un rotundo LGTM! 
te felicito por haberlo terminado!

**Comment by FerDR89** [comment]
> Fer como estas? ahí revise el juego y anda re bien! no note nada raro ni fuera de lugar, así que para mi es un rotundo LGTM!
> te felicito por haberlo terminado!

Gracias Facu!
Nos vemos del otro lado  (?
